stages:
  - build

kaniko:
  stage: build
  tags:
    - docker
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "jammsen/the-forest-dedicated-server:${CI_COMMIT_SHORT_SHA}"
      --no-push
      --tarPath image.tar
  artifacts:
    paths:
      - image.tar
    expire_in: 1 day

 
