services:
  the-forest-dedicated-server:
    container_name: the-forest-dedicated-server
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - SERVER_STEAM_ACCOUNT_TOKEN=${STEAM_TOKEN}
      - SERVER_IP=${IP}
      - SERVER_STEAM_PORT=${STEAM_PORT}
      - SERVER_GAME_PORT=${GAME_PORT}
      - SERVER_QUERY_PORT=${QUERY_PORT}
      - SERVER_PLAYERS=${PLAYERS}
      - SERVER_VAC=${VAC}
      - SERVER_PASSWORD=${PASSWORD}
      - SERVER_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SERVER_AUTO_SAVE_INTERVAL=${AUTO_SAVE_INTERVAL}
      - SERVER_DIFFICULTY=${DIFFICULTY}
      - SERVER_INIT_TYPE=${INIT_TYPE}
      - SERVER_SLOT=${SLOT}
      - SERVER_SHOW_LOGS=${SHOW_LOGS}
      - SERVER_CONTACT=${CONTACT}
      - SERVER_VEGAN_MODE=${VEGAN_MODE}
      - SERVER_VEGETARIAN_MODE=${VEGETARIAN_MODE}
      - SERVER_RESET_HOLES_MODE=${RESET_HOLES_MODE}
      - SERVER_TREE_REGROW_MODE=${TREE_REGROW_MODE}
      - SERVER_ALLOW_BUILDING_DESTRUCTION=${ALLOW_BUILDING_DESTRUCTION}
      - SERVER_ALLOW_ENEMIES_CREATIVE=${ALLOW_ENEMIES_CREATIVE}
      - SERVER_ALLOW_CHEATS=${ALLOW_CHEATS}
      - SERVER_REALISTIC_PLAYER_DAMAGE=${REALISTIC_PLAYER_DAMAGE}
      - SERVER_TARGET_FPS_IDLE=${TARGET_FPS_IDLE}
      - SERVER_TARGET_FPS_ACTIVE=${TARGET_FPS_ACTIVE}
    ports:
      - 8766:8766/tcp
      - 8766:8766/udp
      - 27015:27015/tcp
      - 27015:27015/udp
      - 27016:27016/tcp
      - 27016:27016/udp
    volumes:
      - ./steamcmd:/steamcmd
      - ./game:/theforest
      - ./winedata:/winedata
